apiVersion: v1
kind: LimitRange
metadata:
  name: store-limits
spec:
  limits:
    - type: Container
      default:
        cpu: "{{ .Values.resources.defaults.defaultCpu }}"
        memory: "{{ .Values.resources.defaults.defaultMemory }}"
      defaultRequest:
        cpu: "{{ .Values.resources.defaults.defaultRequestCpu }}"
        memory: "{{ .Values.resources.defaults.defaultRequestMemory }}"
